### PR TITLE
Mar27/16

### PR DESCRIPTION
**Pull request by jitindodd**
there was a syntax error not allowing the server to run on heroku when i deployed it, so i fixed it on da quix

### CODE REVIEW

**Comment by BrentBrightling** [comment]
Jitin can you pull from master, I updated some of the things you fixed I believe

**Comment by jitindodd** [comment]
kk just did, that's weird, I pulled earlier but didn't get these changes,
maybe you didn't merge yet?

On Sun, Mar 27, 2016 at 10:32 PM, Brent Brightling <notifications@github.com

**Comment by BrentBrightling** [comment]
I merged just before I posted that, I had to get approved by Jose

**Comment by jitindodd** [comment]
kk sounds good!

On Sun, Mar 27, 2016 at 11:18 PM, Brent Brightling <notifications@github.com

**Comment by JavierR14** [comment]
LGTM!

**Pull request merged**
